drop database if exists challenge1;

create database challenge1;

CREATE TABLE  ALUMNO(
NOMBRE varchar(30),
APELLIDO varchar(30),
DNIALUMNO INTEGER,
CONSTRAINT PK_ALUMNO PRIMARY KEY (DNIALUMNO));

CREATE TABLE  CURSO(
IDCURSO SERIAL,
NOMBRE varchar(30),
CONSTRAINT PK_CURSO PRIMARY KEY (IDCURSO));


CREATE TABLE IF NOT EXISTS ASISTENCIA(
IDASISTENCIA SERIAL,
DNIALUMNO INTEGER,
NOMBRECLASE varchar(30),
CONSTRAINT PK_ASISTENTE PRIMARY KEY (IDASISTENCIA));


INSERT INTO ALUMNO (NOMBRE,APELLIDO,DNIALUMNO) VALUES ('JOAO','A',11111);
INSERT INTO ALUMNO (NOMBRE,APELLIDO,DNIALUMNO) VALUES ('NEHEMIAS','B',22222);
INSERT INTO ALUMNO (NOMBRE,APELLIDO,DNIALUMNO) VALUES ('CELESTE','X',33333);
INSERT INTO ALUMNO (NOMBRE,APELLIDO,DNIALUMNO) VALUES ('LUCIANA','Z',44444);


INSERT INTO ASISTENCIA(DNIALUMNO,NOMBRECLASE) VALUES(11111,'CURSO-GO');
INSERT INTO ASISTENCIA(DNIALUMNO,NOMBRECLASE) VALUES(33333,'CURSO-GO');

INSERT INTO ASISTENCIA(DNIALUMNO,NOMBRECLASE) VALUES(22222,'CURSO-SPRING');
INSERT INTO ASISTENCIA(DNIALUMNO,NOMBRECLASE) VALUES(44444,'CURSO-SPRING');

select DISTINCT NOMBRE, COUNT(NOMBRE) from curso left join asistencia on curso.NOMBRE=asistencia.nombreclase GROUP BY curso.nombre;

SELECT NOMBRE FROM ALUMNO INNER JOIN ASISTENCIA ON ALUMNO.DNIALUMNO = ASISTENCIA.DNIALUMNO WHERE ASISTENCIA.NOMBRECLASE='CURSO-GO';

INSERT INTO CURSO (NOMBRE) VALUES ('CURSO-GO');
INSERT INTO CURSO (NOMBRE) VALUES ('CURSO-SPRING');